---
title: "session_3"
author: "Albert Camps"
date: "8 de abril de 2015"
output: html_document
runtime: shiny
---
```{r}

library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
spdb <- dbConnect(
 drv,
 host = "jh-redshift.socialpointgames.com",
 port = "5439",
 dbname = "datawarehouse",
 user = "admin",
 password = "rEL2QjKQRq6qDc"
)

install.packages(c("dplyr", "tidyr"))
library(dplyr)
library(tityr)
install.packages("hflights")
library(hflights)

hf_tbl <- tbl_df(hflights)
glimpse(hf_tbl)
filter(hf_tbl, Origin == "IAH")
sample_n(hf_tbl, 5)
sample_frac(hf_tbl, 0.01)
#Select rows by position, by row number
slice(hf_tbl, 10:15)

#Subsetting variables, no more need for $ sign
select(hf_tbl, Year, Month, DayofMonth)

# Order is important
select(hf_tbl, Year:DayofMonth, Origin)

# When you need to find a specific from a few
select(hf_tbl, contains("Delay"))

# magic
select(hf_tbl, one_of("Year", "Month"))

select(hf_tbl, yr = Year, mon = Month) #renaming

# Modifying and creating new ariables
hf_tbl <- mutate(hf_tbl, route = paste(Origin, Dest, sep = "-"))

# You can drop the column you modify using transmute
select (hf_tbl, route)
hf_tbl <- mutate(hf_tbl, route = tolower(route))
```

# Pipes
```{r}
#ugly
hf_tbl <- tbl_df(hflights)
hf_tbl <- filter(hf_tbl, Origin == "IAH")
hf_tbl <- select(hf_tbl, Year:DayofMonth, Origin, Dest, Month)
hf_tbl <- mutate(hf_tbl, route = paste(Origin, Dest, sep = "-"))

#Uglier
tbl_df(
  mutate(
    select(
      filter(
        hflights, Origin == "IAH"),
      Year:DayofMonth, Origin, Dest, -Month),
    route = paste(Origin, Dest, sep = "-")
    ))

# Pipes shift + command + m

#better
hflights %>%
  tbl_df %>%
  filter(Origin == "IAH") %>%
  select(Year:DayofMonth, Origin, Dest, -Month) %>%
  mutate(route = paste(Origin, Dest, sep = "-"))

# grouping / summarizing
avg_delay <- hflights %>%
  tbl_df %>%
  group_by(Origin, Month) %>%
  summarise(
    avg_dep_delay = mean(DepDelay, na.rm = TRUE),
    avg_arr_delay = mean(ArrDelay, na.rm = TRUE)
 ) %>%
  mutate(Month = month.abb[Month])

#sorting
avg_delay <- avg_delay %>%  arrange (desc(avg_dep_delay))

#joining
hflights %>%
 tbl_df %>%
 mutate(Month = month.abb[Month]) %>%
 left_join(avg_delay, by = c("Origin", "Month"))

```

## Exercises

Now we are going to repeat the same exercises we did last week with the new tools.

```{r}
library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
spdb <- dbConnect(
 drv,
 host = "jh-redshift.socialpointgames.com",
 port = "5439",
 dbname = "datawarehouse",
 user = "",
 password = ""
)

jh_users <- dbGetQuery(spdb, "select * from jurassichunter.t_user")
session_query <- "select * from jurassichunter.t_session where date_session_end is not null limit 10000"
jh_session <- dbGetQuery(spdb, session_query)
session_users <- "select * from jurassichunter.t_user where user_id in  "

#users <- unique(select(jh_session, user_id))
users <- unique(jh_session$user_id)
head(users)
count(users)
?paste
users_txt <- paste(users, collapse =", ")

user_query<- paste("select * from jurassichunter.t_user where user_id in (", users_txt,  ")")
jh_user <- dbGetQuery(spdb, user_query)
```

```{r}
session_tbl <- tbl_df(jh_session)
user_tbl <- tbl_df(jh_user)

# select 500 users at random
usersFiveHundred <- sample_n(user_tbl, 500)

# select 20% of users at random
user0 <- user_tbl %>%
  sample_frac(0.2) %>%
# put them together
  bind_rows(usersFiveHundred) %>%
# remove dups
  distinct() %>%

# Select countries and nontesters
filter(register_ip_country %in% c("ES", "AU") & is_tester == F)
library(lubridate)
  session0 <- session_tbl %>%
# keep certain variables
select(user_id, date_session_start, date_session_end, game_end_level) %>%
# remove missing levels
  filter(!is.na(game_end_level)) %>%
  # change class of dates
  mutate(
    date_session_start = ymd_hms(date_session_start),
    date_session_end = ymd_hms(date_session_end)
    ) %>%
  # keep first obs per user
  group_by(user_id) %>%
  top_n(3, date_session_start) %>%
  arrange(user_id, date_session_start)
  

  glimpse(user_tbl)
glimpse(session0)
```



